import test from 'node:test';import assert from 'node:assert/strict';
import { newKey,sign,verify,hash } from '../lib/crypto.ts';
import { makePerson,registration,meeting,agreementPayload,command,publicRoom,tick,resolveRole,type Room } from '../lib/engine.ts';
import { match,shortest,walkerPath } from '../lib/graph.ts';
async function setup(){const now=Date.now(),a=await newKey(),b=await newKey();const A=await makePerson('A',a.publicKey,{origin:'gates',destination:'morewood',leaveAt:now,window:5,detour:2,wait:5},now),B=await makePerson('B',b.publicKey,{origin:'wean',destination:'resnik',leaveAt:now,window:5,detour:2,wait:5},now);const r:Room={id:'test-room',owner:'owner',created:now,expires:now+86400000,rev:0,demo:true,status:'matched',a:A.p,b:B.p,inviteHash:'consumed',plan:match(A.p.intent,B.p.intent),challenges:{},actions:{},events:[]};
 for(const role of ['A','B'] as const){const k=role==='A'?a:b;await command(r,role,'register',{signature:await sign(k.pair.privateKey,registration(r,role))});await command(r,role,'accept',{});}
 await command(r,'A','scan',{payload:meeting(r,'B'),signature:await sign(b.pair.privateKey,meeting(r,'B'))});await command(r,'B','scan',{payload:meeting(r,'A'),signature:await sign(a.pair.privateKey,meeting(r,'A'))});
 for(const role of ['A','B'] as const){const k=role==='A'?a:b;await command(r,role,'agreement',{signature:await sign(k.pair.privateKey,agreementPayload(r,role))});}
 async function action(role:'A'|'B',action:string,payload:any={}){const c=await command(r,role,'challenge',{action,payload});const signature=await sign((role==='A'?a:b).pair.privateKey,c.envelope);const result=await command(r,role,'action',{envelope:c.envelope,signature});return {result,envelope:c.envelope,signature};}return {r,a,b,A,B,action};}
test('different destinations share a contiguous useful route',async()=>{const {r}=await setup();assert.ok(r.plan);assert.ok(r.plan.minutes>=4);assert.ok(r.plan.extraA<=2&&r.plan.extraB<=2);assert.equal(r.status,'active');assert.equal(r.agreementHash,await hash(r.agreement));});
test('no detour matching rejects reverse journeys',()=>{const now=Date.now(),a={origin:'gates',destination:'morewood',leaveAt:now,window:0,detour:0,wait:0},b={...a,origin:'morewood',destination:'gates'};assert.equal(match(a,b),null);});
test('nonoverlapping time windows cannot match',()=>{const now=Date.now(),a={origin:'gates',destination:'morewood',leaveAt:now,window:0,detour:0,wait:0},b={...a,origin:'wean',destination:'resnik',leaveAt:now+1800000};assert.equal(match(a,b),null);});
test('graph routes walk along connected edges',()=>{const p=shortest('gates','morewood');assert.deepEqual(p.path,['gates','cut','forbes','morewood']);assert.equal(p.minutes,8);});
test('personal path uses own endpoints plus the shared plan',()=>{
 const now=Date.now(),a={origin:'gates',destination:'morewood',leaveAt:now,window:5,detour:2,wait:5},b={origin:'wean',destination:'resnik',leaveAt:now,window:5,detour:2,wait:5};
 const plan=match(a,b);assert.ok(plan);
 const pathA=walkerPath(a.origin,a.destination,plan);
 assert.equal(pathA[0],'gates');assert.equal(pathA.at(-1),'morewood');
 assert.ok(pathA.includes(plan.meeting));assert.ok(pathA.includes(plan.split));
 assert.equal('pathA' in plan,false);assert.equal('pathB' in plan,false);
});
test('a changed agreement invalidates existing signatures',async()=>{const {r,a}=await setup();const changed=structuredClone(r.agreement);changed.plan.split='oakland';assert.equal(await verify(a.publicKey,{...agreementPayload(r,'A'),agreementHash:await hash(changed)},r.a.agreementSignature!),false);});
test('companion cannot forge an arrival',async()=>{const {r,b}=await setup();const c=await command(r,'A','challenge',{action:'ARRIVE',payload:{}});await assert.rejects(()=>command(r,'A','action',{envelope:c.envelope,signature:signFake}),/Signature rejected/);const signature=await sign(b.pair.privateKey,c.envelope);await assert.rejects(()=>command(r,'A','action',{envelope:c.envelope,signature}),/Signature rejected/);assert.equal(r.a.arrived,false);});
const signFake='AAAA';
test('a repeated action is idempotent without advancing sequence',async()=>{const {r,action}=await setup();const sent=await action('A','CHECK_IN');const repeat=await command(r,'A','action',sent);assert.equal(repeat.replayed,true);assert.equal(r.a.seq,1);assert.equal(Object.keys(r.actions).length,1);});
test('changed payload cannot reuse consumed challenge',async()=>{const {r,a,action}=await setup();const sent=await action('A','CHECK_IN');const changed={...sent.envelope,action:'ARRIVE'};await assert.rejects(async()=>command(r,'A','action',{envelope:changed,signature:await sign(a.pair.privateKey,changed)}),/Action ID was reused/);});
test('stale challenge is rejected even with a valid signature',async()=>{const {r,a}=await setup();const c=await command(r,'A','challenge',{action:'CHECK_IN',payload:{}});const signature=await sign(a.pair.privateKey,c.envelope);await assert.rejects(()=>command(r,'A','action',{envelope:c.envelope,signature},c.envelope.expires+1),/expired/);});
test('cross-session action cannot change state',async()=>{const {r,a}=await setup();const c=await command(r,'A','challenge',{action:'ARRIVE',payload:{}});c.envelope={...c.envelope,room:'different-room'};const signature=await sign(a.pair.privateKey,c.envelope);await assert.rejects(()=>command(r,'A','action',{envelope:c.envelope,signature}),/another participant or walk/);});
test('contact must accept before arming a timer',async()=>{const {action}=await setup();await assert.rejects(()=>action('A','ARM_TIMER',{minutes:15,demo:false}),/contact must accept/);});
test('leaving preserves own timer; arrival independently resolves it',async()=>{const {r,action}=await setup();await command(r,'TA','contact-accept',{});await action('A','ARM_TIMER',{minutes:15,demo:false});await action('B','LEAVE');assert.equal(r.a.timer?.state,'armed');assert.equal(r.status,'closed');await action('A','ARRIVE',{version:1});assert.equal(r.a.timer?.state,'arrived');assert.equal(r.b?.arrived,false);});
test('durable deadline produces one incident and late arrival resolves it',async()=>{const {r,action}=await setup();await command(r,'TA','contact-accept',{});await action('A','ARM_TIMER',{minutes:1,demo:true});assert.equal(tick(r,r.a.timer!.due+1),true);const at=r.a.timer!.alertedAt;assert.equal(tick(r,r.a.timer!.due+2),false);assert.equal(r.a.timer!.alertedAt,at);await command(r,'TA','acknowledge',{});await action('A','ARRIVE',{version:1});assert.equal(r.a.timer!.state,'arrived');assert.ok(r.a.timer!.ackAt);});
test('companion API view does not leak destination or timer',async()=>{const {r,action}=await setup();await command(r,'TA','contact-accept',{});await action('A','ARM_TIMER',{minutes:1,demo:false});const v=publicRoom(r,'B') as any;assert.equal(v.peer.intent,undefined);assert.equal(v.peer.timer,undefined);assert.equal(JSON.stringify(v).includes('contactInviteHash'),false);});
test('contacts cannot submit walker actions',async()=>{const {r}=await setup();await assert.rejects(()=>command(r,'TA','challenge',{action:'ARRIVE'}),/Contacts cannot act/);});
test('unknown device tokens are denied',async()=>{const {r,A}=await setup();assert.equal(await resolveRole(r,A.token),'A');await assert.rejects(()=>resolveRole(r,'bad-token'),/does not have access/);});
test('new active signing key cannot replace a registered key',async()=>{const {r}=await setup();await assert.rejects(()=>command(r,'A','register',{signature:'replacement'}),/already registered/);});

