import { hash,random,verify,canon } from './crypto.ts';
import { match,type Intent,type Plan,nodes } from './graph.ts';
export type WalkerRole='A'|'B';export type Role=WalkerRole|'TA'|'TB';
export type Timer={state:'armed'|'alerted'|'arrived'|'cancelled';due:number;grace:number;version:number;alertedAt?:number;ackAt?:number;resolvedAt?:number;demo:boolean};
export type Participant={name:string;pub:string;tokenHash:string;registration:string;registered:boolean;intent:Intent;accepted:boolean;meetingNonce:string;meetingExpires:number;scanned:boolean;meetingProof?:{payload:any;signature:string};agreementSignature?:string;seq:number;left:boolean;arrived:boolean;checkAt?:number;timer?:Timer;contactAccepted:boolean;contactHash?:string;contactInviteHash:string};
export type Room={id:string;owner:string;created:number;expires:number;rev:number;demo:boolean;status:string;a:Participant;b?:Participant;inviteHash:string;plan:Plan|null;agreement?:any;agreementHash?:string;challenges:Partial<Record<WalkerRole,any>>;actions:Record<string,{digest:string;result:any;envelope:any;signature:string}>;events:{id:string;text:string;at:number}[]};
export class Fault extends Error { constructor(message:string,public status=400){super(message);} }
const assert=(v:unknown,m:string,status=400)=>{if(!v)throw new Fault(m,status);};
export const person=(r:Room,role:Role)=>role==='A'||role==='TA'?r.a:r.b;
export function validateIntent(i:Intent){assert(i&&nodes.some(n=>n.id===i.origin)&&nodes.some(n=>n.id===i.destination)&&i.origin!==i.destination,'Choose two different campus locations.');assert(Number.isFinite(i.leaveAt)&&Math.abs(i.leaveAt-Date.now())<3600000,'Choose a departure within the next hour.');for(const k of ['window','detour','wait'] as const)assert(Number.isFinite(i[k])&&i[k]>=0&&i[k]<=15,'Invalid walking preference.');}
export function event(r:Room,text:string,now=Date.now()){r.events.unshift({id:random().slice(0,12),text,at:now});r.events=r.events.slice(0,40);}
export async function makePerson(name:string,pub:string,intent:Intent,now:number){validateIntent(intent);assert(typeof name==='string'&&name.trim().length>0&&name.length<=40,'Enter a name of 1–40 characters.');assert(typeof pub==='string'&&pub.length===87,'Invalid device public key.');const token=random(),contactInvite=random();const p:Participant={name:name.trim(),pub,tokenHash:await hash(token),registration:random(),registered:false,intent,accepted:false,meetingNonce:random(),meetingExpires:now+120000,scanned:false,seq:0,left:false,arrived:false,contactAccepted:false,contactInviteHash:await hash(contactInvite)};return {p,token,contactInvite};}
export function registration(r:Room,role:WalkerRole){const p=person(r,role)!;return {domain:'nightwalk.register.v1',room:r.id,role,publicKey:p.pub,challenge:p.registration};}
export function meeting(r:Room,role:WalkerRole){const p=person(r,role)!;return {domain:'nightwalk.meeting.v1',room:r.id,role,publicKey:p.pub,nonce:p.meetingNonce,expires:p.meetingExpires};}
export function agreementPayload(r:Room,role:WalkerRole){return {domain:'nightwalk.agreement-signature.v1',room:r.id,role,agreementHash:r.agreementHash};}
export async function buildAgreement(r:Room){assert(r.plan&&r.b,'No compatible shared route.');r.agreement={domain:'nightwalk.agreement.v1',room:r.id,revision:1,participants:[{role:'A',keyId:await hash(r.a.pub)},{role:'B',keyId:await hash(r.b!.pub)}],plan:r.plan,meetingNonces:[r.a.meetingNonce,r.b!.meetingNonce]};r.agreementHash=await hash(r.agreement);}
export function tick(r:Room,now=Date.now()){let changed=false;for(const p of [r.a,r.b])if(p?.timer?.state==='armed'&&now>=p.timer.due+p.timer.grace){p.timer.state='alerted';p.timer.alertedAt=now;changed=true;}return changed;}
export async function resolveRole(r:Room,token:string):Promise<Role>{const h=await hash(token);if(h===r.a.tokenHash)return 'A';if(h===r.b?.tokenHash)return 'B';if(h===r.a.contactHash)return 'TA';if(h===r.b?.contactHash)return 'TB';throw new Fault('This device does not have access to this walk.',403);}
export function publicRoom(r:Room,role:Role){const p=person(r,role)!;if(role==='TA'||role==='TB')return {id:r.id,role,name:p.name,contactAccepted:p.contactAccepted,timer:p.timer??null,demo:r.demo};
 const peer=person(r,role==='A'?'B':'A');const sharedOpen=!!peer&&!p.left&&!peer.left;
 return {id:r.id,role,status:r.status,rev:r.rev,demo:r.demo,created:r.created,expires:r.expires,me:{name:p.name,registered:p.registered,intent:p.intent,accepted:p.accepted,scanned:p.scanned,seq:p.seq,left:p.left,arrived:p.arrived,pub:p.pub,timer:p.timer??null,contactAccepted:p.contactAccepted,checkAt:p.checkAt},peer:peer?{name:peer.name,registered:peer.registered,accepted:peer.accepted,scanned:peer.scanned,left:peer.left,pub:peer.pub,checkAt:sharedOpen?peer.checkAt:undefined}:null,plan:r.plan,agreement:r.agreement,agreementHash:r.agreementHash,signatures:{A:r.a.agreementSignature,B:r.b?.agreementSignature},registration:!p.registered?registration(r,role):null,meeting:p.registered&&p.accepted?meeting(r,role):null,events:r.events,serverTime:Date.now()};
}
export async function command(r:Room,role:Role,op:string,b:any,now=Date.now()){
 const p=person(r,role)!;assert(p,'Participant not found.');
 if(role==='TA'||role==='TB'){if(op==='contact-accept'){p.contactAccepted=true;return {accepted:true};}if(op==='acknowledge'){assert(p.timer?.state==='alerted','No overdue check-in to acknowledge.');p.timer!.ackAt=now;return {acknowledged:true};}throw new Fault('Contacts cannot act for a walker.',403);}
 const wr=role as WalkerRole,peer=person(r,wr==='A'?'B':'A');
 if(op==='register'){assert(!p.registered,'Device already registered.');assert(await verify(p.pub,registration(r,wr),b.signature),'Device signature did not verify.');p.registered=true;event(r,`${p.name}'s device registered`,now);return {registered:true};}
 assert(p.registered,'Register this device first.');
 if(op==='accept'){assert(r.status==='matched'&&r.plan&&!p.accepted,'This offer is no longer available.');p.accepted=true;if(peer?.accepted){r.status='meeting';for(const q of [p,peer]){q.meetingExpires=now+120000;q.meetingNonce=random();}await buildAgreement(r);}event(r,`${p.name} accepted the shared route`,now);return {accepted:true};}
 if(op==='decline'){assert(['waiting','matched','meeting'].includes(r.status),'This walk has already started.');r.status='cancelled';event(r,`${p.name} cancelled the proposal`,now);return {cancelled:true};}
 if(op==='refresh-meeting'){assert(r.status==='meeting'&&!r.a.agreementSignature&&!r.b?.agreementSignature,'The agreement is already being signed.');for(const q of [p,peer!]){q.meetingNonce=random();q.meetingExpires=now+120000;q.scanned=false;q.meetingProof=undefined;}await buildAgreement(r);return {refreshed:true};}
 if(op==='scan'){assert(r.status==='meeting'&&peer?.registered,'Both devices must accept first.');assert(canon(b.payload)===canon(meeting(r,wr==='A'?'B':'A')),'That code belongs to another or expired meeting.');assert(now<=peer!.meetingExpires,'Meeting code expired. Refresh the meeting codes.');assert(await verify(peer!.pub,b.payload,b.signature),'Companion QR signature did not verify.');p.scanned=true;p.meetingProof={payload:b.payload,signature:b.signature};return {verified:true};}
 if(op==='agreement'){assert(r.status==='meeting'&&p.scanned&&peer?.scanned,'Both walkers must confirm the meeting codes first.');assert(await verify(p.pub,agreementPayload(r,wr),b.signature),'Agreement signature did not verify.');p.agreementSignature=b.signature;if(peer?.agreementSignature){r.status='active';event(r,'Both devices signed the same walking agreement',now);}return {verified:true};}
 if(op==='challenge'){
 assert(['active','closed'].includes(r.status),'Confirm the walking agreement first.');const allowed=['CHECK_IN','LEAVE','ARRIVE','ARM_TIMER','EXTEND_TIMER','CANCEL_TIMER'];assert(allowed.includes(b.action),'Unknown action.');
 const c={domain:'nightwalk.action.v1',room:r.id,role:wr,agreementHash:r.agreementHash,sequence:p.seq+1,actionId:random(),action:b.action,payload:b.payload??{},nonce:random(),expires:now+60000};r.challenges[wr]=c;return {envelope:c};
 }
 if(op==='action'){
 const e=b.envelope;assert(e&&typeof e.actionId==='string','Missing action envelope.');assert(e.room===r.id&&e.role===wr&&e.agreementHash===r.agreementHash,'Action belongs to another participant or walk.');assert(await verify(p.pub,e,b.signature),'Signature rejected: this action was not signed by your device.');const digest=await hash(e),key=wr+':'+e.actionId;const old=r.actions[key];if(old){assert(old.digest===digest,'Action ID was reused with different data.');return {...old.result,replayed:true};}
 assert(canon(e)===canon(r.challenges[wr]),'Challenge is missing, consumed, or changed.');assert(now<=e.expires,'Action expired. Please try again.');assert(e.sequence===p.seq+1,'Action order changed. Refresh and try again.');assert(Object.keys(r.actions).length<400,'This demo session has reached its action limit.');
 const payload=e.payload;assert(payload&&typeof payload==='object'&&!Array.isArray(payload),'Invalid action payload.');const keys=Object.keys(payload).sort().join(',');
 if(e.action==='CHECK_IN'){assert(keys==='','Unexpected check-in data.');assert(!p.left&&!peer?.left&&r.status==='active','The shared walk has ended.');p.checkAt=now;event(r,`${p.name} signed a check-in`,now);}
 else if(e.action==='LEAVE'){assert(keys==='','Unexpected departure data.');assert(!p.left,'You already left this shared walk.');p.left=true;r.status='closed';event(r,`${p.name} ended the shared walk`,now);}
 else if(e.action==='ARM_TIMER'){assert(keys==='demo,minutes','Invalid timer settings.');assert(p.contactAccepted,'Your contact must accept the invitation first.');assert(!p.timer&&!p.arrived,'An arrival timer already exists or arrival is confirmed.');assert(typeof payload.demo==='boolean'&&Number.isFinite(payload.minutes)&&payload.minutes>=1&&payload.minutes<=120,'Choose 1–120 minutes.');p.timer={state:'armed',due:now+(payload.demo?30000:payload.minutes*60000),grace:payload.demo?0:300000,version:1,demo:payload.demo};}
 else if(e.action==='EXTEND_TIMER'){assert(keys==='minutes,version','Invalid timer extension.');assert(p.timer?.state==='armed'&&payload.version===p.timer.version,'Timer changed or is already overdue.');assert(Number.isFinite(payload.minutes)&&payload.minutes>=1&&payload.minutes<=30,'Choose a 1–30 minute extension.');p.timer!.due+=payload.minutes*60000;p.timer!.version++;}
 else if(e.action==='CANCEL_TIMER'){assert(keys==='version','Invalid timer cancellation.');assert(p.timer?.state==='armed'&&payload.version===p.timer.version,'Timer changed or cannot be cancelled.');p.timer!.state='cancelled';p.timer!.version++;}
 else if(e.action==='ARRIVE'){assert(!p.arrived,'Arrival is already confirmed.');if(p.timer&&['armed','alerted'].includes(p.timer.state)){assert(keys==='version'&&payload.version===p.timer.version,'Include the current timer version.');p.timer.state='arrived';p.timer.resolvedAt=now;p.timer.version++;}else assert(keys==='','Unexpected arrival data.');p.arrived=true;p.left=true;r.status='closed';event(r,`${p.name} ended their participation`,now);}
 else throw new Fault('Unknown signed action.');
 p.seq++;delete r.challenges[wr];const result={accepted:true,sequence:p.seq,action:e.action,receivedAt:now};r.actions[key]={digest,result,envelope:e,signature:b.signature};return result;
 }
 if(op==='inspect'){const valid=await verify(p.pub,b.envelope,b.signature);const recorded=r.actions[wr+':'+b.envelope?.actionId];return {signatureValid:valid,alreadyRecorded:!!recorded,scopeValid:b.envelope?.room===r.id&&b.envelope?.role===wr};}
 throw new Fault('Unknown operation.',404);
}
