import { env } from 'cloudflare:workers';
import { type Room,tick,Fault } from './engine.ts';
export function database(){if(!env.DB)throw new Fault('Walk storage is temporarily unavailable.',503);return env.DB as D1Database;}
export function nextDue(r:Room){const due=[r.a.timer,r.b?.timer].filter(t=>t?.state==='armed').map(t=>t!.due+t!.grace);return due.length?Math.min(...due):null;}
export async function loadRoom(id:string,owner:string){const row=await database().prepare('SELECT state, revision FROM walks WHERE id = ? AND owner = ? AND expires > ?').bind(id,owner,Date.now()).first<{state:string;revision:number}>();if(!row)throw new Fault('Walk not found or expired.',404);const r=JSON.parse(row.state) as Room;r.rev=row.revision;return r;}
export async function loadRoomById(id:string){const row=await database().prepare('SELECT state, revision FROM walks WHERE id = ? AND expires > ?').bind(id,Date.now()).first<{state:string;revision:number}>();if(!row)throw new Fault('Walk not found or expired.',404);const r=JSON.parse(row.state) as Room;r.rev=row.revision;return r;}
export async function saveRoom(r:Room){const rev=r.rev;r.rev++;const result=await database().prepare('UPDATE walks SET state = ?, revision = ?, next_due = ? WHERE id = ? AND owner = ? AND revision = ?').bind(JSON.stringify(r),r.rev,nextDue(r),r.id,r.owner,rev).run();return result.meta.changes===1;}
export async function updateRoom<T>(id:string,owner:string,fn:(r:Room)=>Promise<T>){for(let i=0;i<5;i++){const r=await loadRoom(id,owner);tick(r);const result=await fn(r);if(await saveRoom(r))return {r,result};}throw new Fault('Another device just updated this walk. Please retry.',409);}
export async function updateRoomById<T>(id:string,fn:(r:Room)=>Promise<T>){for(let i=0;i<5;i++){const r=await loadRoomById(id);tick(r);const result=await fn(r);if(await saveRoom(r))return {r,result};}throw new Fault('Another device just updated this walk. Please retry.',409);}
export async function sweep(){const db=database(),now=Date.now();const rows=await db.prepare('SELECT id, owner FROM walks WHERE next_due <= ? LIMIT 100').bind(now).all<{id:string;owner:string}>();for(const row of rows.results){try{await updateRoom(row.id,row.owner,async r=>tick(r,now));}catch(e){console.error('Timer sweep failed',row.id,e instanceof Error?e.message:'unknown');}}await db.prepare('DELETE FROM walks WHERE expires <= ?').bind(now).run();}
